FROM openjdk:8
COPY ./target/messaging-service-0.0.1-SNAPSHOT.jar messaging-service-0.0.1-SNAPSHOT.jar
COPY ./wait-for-it.sh wait-for-it.sh 
RUN chmod +x wait-for-it.sh
CMD ["./wait-for-it.sh" , "user-service:7200" , "--strict" , "--timeout=275" , "--" , "java", "-jar", "messaging-service-0.0.1-SNAPSHOT.jar"]